# Generated by Django 3.1.4 on 2020-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('s_type', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
