# Generated by Django 3.1.4 on 2020-12-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('B', 'Bass'), ('L', 'Lead'), ('P', 'Pad')], default='B', max_length=1)),
                ('author', models.CharField(max_length=50)),
                ('synth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.synth')),
            ],
        ),
    ]
