# Generated by Django 3.1.4 on 2020-12-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_patch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='patch',
            name='category',
            field=models.CharField(choices=[('B', 'Bass'), ('L', 'Lead'), ('P', 'Pad'), {'DrumKit', 'K'}], default='B', max_length=7),
        ),
    ]
