# Generated by Django 3.1.4 on 2020-12-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201221_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='category',
            field=models.CharField(choices=[('B', 'Bass'), ('L', 'Lead'), ('P', 'Pad'), {'K', 'DrumKit'}], default='B', max_length=1),
        ),
    ]
