# Generated by Django 3.1.4 on 2020-12-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201221_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='synth',
            name='artists',
            field=models.ManyToManyField(to='main_app.Artist'),
        ),
    ]
