# Generated by Django 3.1.4 on 2020-12-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_synth_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synth',
            name='artists',
        ),
    ]
