# Generated by Django 3.1.4 on 2020-12-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_synth_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='synth',
            name='artists',
            field=models.ManyToManyField(to='main_app.Artist'),
        ),
    ]
